#!/usr/bin/env bash                                                                                                         
# Viewing lg file contents                                                        
cat apache-access.log | awk '{print $1, $9}' | sort | uniq -c | sort -nr
